# Generated by Django 4.1.7 on 2023-04-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_posts_cover_pic_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cover_pic',
            field=models.ImageField(blank=True, default='/profilepics/cover.png', upload_to='coverpic'),
        ),
    ]
