# Generated by Django 4.1.7 on 2023-05-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_posts_cover_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='cover_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_pic',
            field=models.ImageField(blank=True, default='/profilepics/cover', upload_to='coverpic'),
        ),
    ]
